### ISSUE TITLE
Unable to navigate based on links in embedded resource

### ISSUE THREAD

**Issue by nningego** [jimmythompson/halboy#1]
I'd like to be able to fetch a resource containing embedded resources and navigate based on the links contained in the embedded resource:

```clojure
{
  "_embedded": {
    "thing": {
      "_links": {
        ...
        "other": "https://example.com/other/thing"
      }
    }
  }
}
```

```clojure
(let [discovery-result (navigator/discover address)
      thing-resource (hal/get-resource (navigator/resource discovery-result))
      other-result (navigator/get (navigator/from thing-resource))]
  (println (navigator/resource other-result)))
```

Not sure what the API for this should look like but it seems being able to continue navigating from an existing resource would be beneficial in other cases as well.

I hereby take issue with halboy.

**Comment by tobyclemson** [comment]
I too take issue with halboy.

**Comment by jimmythompson** [comment]
In a world where we only have singular resources, it could look like this:

```clojure
(let [discovery-result (navigator/discover "https://example.com")
      thing-resource (navigator/get-embedded discovery-result :thing)
      other-result (navigator/get thing-resource :other)]
  (println (navigator/resource other-result)))
```

`get-embedded` would give you a navigator pointing at the embedded resource. It could make the call to actually get that content (by calling the self link), or not, based on your settings.

Dunno how this would work where you get a list of resources though. Ideally it would take a function which takes the list of resources under a given key, filters them, and return a navigator for the one you chose. If the filter didn't selects more than one, it could throw, saying your selection is too broad.

**Comment by tobyclemson** [comment]
Maybe just returning a seq of navigators would be the best approach in the case of a list as that allows the consumer to just treat it as data and filter however they like.

**Comment by jimmythompson** [comment]
```clojure
(let [users (-> (navigator/discover "https://example.com")
                (navigator/get :users)
                (navigator/resource)
                (hal/get-resource :users))
      navigators (map navigator/resume users)]
  ; do something with our newfound navigators
)
```

In 2.0.0, the navigator now supports resuming from a HAL resource. Obviously it's not ideal, options you passed when you called `discover` would need to be re-entered, but would this do for now?
